Revert the Java version for the soft-opt-in-consent-setter lambdas
We think this may be the cause for requests to IDAPI failing. We're
seeing the following in the logs in PROD:
IdentityConnector: Identity request failed:
java.lang.reflect.InaccessibleObjectException: Unable to make field
private final sun.net.www.protocol.https.DelegateHttpsURLConnection
sun.net.www.protocol.https.HttpsURLConnectionImpl.delegate accessible:
module java.base does not "opens sun.net.www.protocol.https" to unnamed
module @6cc4c815